default:
  @just --list

env:
  nix develop

# build
b name:
  # 参数 `-l tlpi` 表示在编译时，要将我们之前放入到系统依赖目录中的 `libtlpi.a` 静态库链接进来，
  # 如果缺少这个参数，部分使用了 `tlpi_hdr.h` 的程序将无法通过编译。
  # 使用该头文件与静态库的主要目的是与书中代码一致，写出来的代码也更简化些，降低了门槛。
  #（实际上完全可以不依赖该静态库、不使用 `tlpi_hdr.h`）
  #
  # 而 `-Wall` 则表示显示所有 warning 级别的编译提示，这对判断运行期错误的位置跟原因很有帮助。
  # 
  # 最后 `--debug` 是在编译得到的程序中添加代码相关信息，在出问题时方便调试。
  gcc {{name}}.c -o {{name}}.out -l tlpi  -Wall --debug

# build via nix env
nb name:
  # NOTE: the `gcc` command used here is a wrapper provided by nix,
  # which will consume the `NIX_CFLAGS_COMPILE` and `NIX_LDFLAGS` env vars to include the headers and link the libraries
  nix develop --command gcc {{name}}.c -o {{name}}.out -l tlpi  -Wall --debug

